apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-react-pro
  name: hello-react-svc
  namespace: production
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: hello-react-pro